import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { ModeProvider } from "@/providers/mode-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mt-20">
        <ModeProvider>
          <Header />
          {children}
        </ModeProvider>
      </body>
    </html>
  );
}
