name: Deploy Asst's Study Project With GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Check package.json build script
        run: |
          cd apps/agency-landing-page
          cat package.json

      - name: Build CSS Library Study
        run: |
          cd apps/agency-landing-page
          yarn build

      - name: List all directories and files after build
        run: |
          find apps -type f | grep -v "node_modules" | sort
          find apps -type d | grep -v "node_modules" | sort

      - name: Upload Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/agency-landing-page/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
